###################################################################

# Created by write_sdc on Mon Jan 20 21:51:43 2020

###################################################################
set sdc_version 1.9

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_load -pin_load 3.40189 [get_ports s_tc_hmode]
set_load -pin_load 3.40189 [get_ports s_tc_vmode]
set_load -pin_load 3.40189 [get_ports s_tc_res]
set_load -pin_load 3.40189 [get_ports s_tc_npu_ptr]
set_load -pin_load 3.40189 [get_ports s_tc_tilev]
set_load -pin_load 3.40189 [get_ports s_tc_tileh]
set_load -pin_load 3.40189 [get_ports s_tc_ifmaps]
set_load -pin_load 3.40189 [get_ports s_tc_ofmaps]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[31]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[30]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[29]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[28]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[27]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[26]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[25]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[24]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[23]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[22]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[21]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[20]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[19]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[18]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[17]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[16]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[15]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[14]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[13]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[12]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[11]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[10]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[9]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[8]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[7]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[6]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[5]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[4]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[3]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[2]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[1]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[0]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[9]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[8]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[7]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[6]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[5]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[4]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[3]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[2]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[1]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[0]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[9]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[8]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[7]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[6]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[5]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[4]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[3]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[2]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[1]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[0]}]
set_load -pin_load 3.40189 [get_ports i_data_ev_odd_n]
set_load -pin_load 3.40189 [get_ports {o_data[63]}]
set_load -pin_load 3.40189 [get_ports {o_data[62]}]
set_load -pin_load 3.40189 [get_ports {o_data[61]}]
set_load -pin_load 3.40189 [get_ports {o_data[60]}]
set_load -pin_load 3.40189 [get_ports {o_data[59]}]
set_load -pin_load 3.40189 [get_ports {o_data[58]}]
set_load -pin_load 3.40189 [get_ports {o_data[57]}]
set_load -pin_load 3.40189 [get_ports {o_data[56]}]
set_load -pin_load 3.40189 [get_ports {o_data[55]}]
set_load -pin_load 3.40189 [get_ports {o_data[54]}]
set_load -pin_load 3.40189 [get_ports {o_data[53]}]
set_load -pin_load 3.40189 [get_ports {o_data[52]}]
set_load -pin_load 3.40189 [get_ports {o_data[51]}]
set_load -pin_load 3.40189 [get_ports {o_data[50]}]
set_load -pin_load 3.40189 [get_ports {o_data[49]}]
set_load -pin_load 3.40189 [get_ports {o_data[48]}]
set_load -pin_load 3.40189 [get_ports {o_data[47]}]
set_load -pin_load 3.40189 [get_ports {o_data[46]}]
set_load -pin_load 3.40189 [get_ports {o_data[45]}]
set_load -pin_load 3.40189 [get_ports {o_data[44]}]
set_load -pin_load 3.40189 [get_ports {o_data[43]}]
set_load -pin_load 3.40189 [get_ports {o_data[42]}]
set_load -pin_load 3.40189 [get_ports {o_data[41]}]
set_load -pin_load 3.40189 [get_ports {o_data[40]}]
set_load -pin_load 3.40189 [get_ports {o_data[39]}]
set_load -pin_load 3.40189 [get_ports {o_data[38]}]
set_load -pin_load 3.40189 [get_ports {o_data[37]}]
set_load -pin_load 3.40189 [get_ports {o_data[36]}]
set_load -pin_load 3.40189 [get_ports {o_data[35]}]
set_load -pin_load 3.40189 [get_ports {o_data[34]}]
set_load -pin_load 3.40189 [get_ports {o_data[33]}]
set_load -pin_load 3.40189 [get_ports {o_data[32]}]
set_load -pin_load 3.40189 [get_ports {o_data[31]}]
set_load -pin_load 3.40189 [get_ports {o_data[30]}]
set_load -pin_load 3.40189 [get_ports {o_data[29]}]
set_load -pin_load 3.40189 [get_ports {o_data[28]}]
set_load -pin_load 3.40189 [get_ports {o_data[27]}]
set_load -pin_load 3.40189 [get_ports {o_data[26]}]
set_load -pin_load 3.40189 [get_ports {o_data[25]}]
set_load -pin_load 3.40189 [get_ports {o_data[24]}]
set_load -pin_load 3.40189 [get_ports {o_data[23]}]
set_load -pin_load 3.40189 [get_ports {o_data[22]}]
set_load -pin_load 3.40189 [get_ports {o_data[21]}]
set_load -pin_load 3.40189 [get_ports {o_data[20]}]
set_load -pin_load 3.40189 [get_ports {o_data[19]}]
set_load -pin_load 3.40189 [get_ports {o_data[18]}]
set_load -pin_load 3.40189 [get_ports {o_data[17]}]
set_load -pin_load 3.40189 [get_ports {o_data[16]}]
set_load -pin_load 3.40189 [get_ports {o_data[15]}]
set_load -pin_load 3.40189 [get_ports {o_data[14]}]
set_load -pin_load 3.40189 [get_ports {o_data[13]}]
set_load -pin_load 3.40189 [get_ports {o_data[12]}]
set_load -pin_load 3.40189 [get_ports {o_data[11]}]
set_load -pin_load 3.40189 [get_ports {o_data[10]}]
set_load -pin_load 3.40189 [get_ports {o_data[9]}]
set_load -pin_load 3.40189 [get_ports {o_data[8]}]
set_load -pin_load 3.40189 [get_ports {o_data[7]}]
set_load -pin_load 3.40189 [get_ports {o_data[6]}]
set_load -pin_load 3.40189 [get_ports {o_data[5]}]
set_load -pin_load 3.40189 [get_ports {o_data[4]}]
set_load -pin_load 3.40189 [get_ports {o_data[3]}]
set_load -pin_load 3.40189 [get_ports {o_data[2]}]
set_load -pin_load 3.40189 [get_ports {o_data[1]}]
set_load -pin_load 3.40189 [get_ports {o_data[0]}]
create_clock [get_ports ck]  -name MY_CLK  -period 4  -waveform {0 2}
set_clock_uncertainty 0.07  [get_clocks MY_CLK]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports rst]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_gamma[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_gamma[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_gamma[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_gamma[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_gamma[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_gamma[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_gamma[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_gamma[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_beta[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_beta[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_beta[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_beta[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_beta[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_beta[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_beta[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_beta[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_npu[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_npu[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_npu[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ckg[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ckg[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ckg[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_k[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_k[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_k[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_tile[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_tile[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ifmaps[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ifmaps[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ifmaps[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ofmaps[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ofmaps[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ofmaps[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ofmaps[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_en_npu]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_ldh_v_n]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_en_hmode]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_en_vmode]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_wr_pipe]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_hmode]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_vmode]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_res]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_npu_ptr]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_tilev]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_tileh]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_ifmaps]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_ofmaps]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports i_data_ev_odd_n]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[63]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[62]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[61]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[60]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[59]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[58]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[57]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[56]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[55]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[54]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[53]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[52]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[51]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[50]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[49]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[48]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[47]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[46]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[45]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[44]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[43]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[42]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[41]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[40]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[39]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[38]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[37]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[36]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[35]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[34]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[33]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[32]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[0]}]
