###################################################################

# Created by write_sdc on Sat Jan 18 22:47:04 2020

###################################################################
set sdc_version 1.9

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_load -pin_load 3.40189 [get_ports s_tc_hmode]
set_load -pin_load 3.40189 [get_ports s_tc_vmode]
set_load -pin_load 3.40189 [get_ports s_tc_res]
set_load -pin_load 3.40189 [get_ports s_tc_npu_ptr]
set_load -pin_load 3.40189 [get_ports s_tc_tilev]
set_load -pin_load 3.40189 [get_ports s_tc_tileh]
set_load -pin_load 3.40189 [get_ports s_tc_ifmaps]
set_load -pin_load 3.40189 [get_ports s_tc_ofmaps]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[9]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[8]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[7]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[6]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[5]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[4]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[3]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[2]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[1]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[0]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[9]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[8]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[7]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[6]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[5]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[4]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[3]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[2]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[1]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[0]}]
set_load -pin_load 3.40189 [get_ports i_data_ev_odd_n]
set_load -pin_load 3.40189 [get_ports {o_data[127]}]
set_load -pin_load 3.40189 [get_ports {o_data[126]}]
set_load -pin_load 3.40189 [get_ports {o_data[125]}]
set_load -pin_load 3.40189 [get_ports {o_data[124]}]
set_load -pin_load 3.40189 [get_ports {o_data[123]}]
set_load -pin_load 3.40189 [get_ports {o_data[122]}]
set_load -pin_load 3.40189 [get_ports {o_data[121]}]
set_load -pin_load 3.40189 [get_ports {o_data[120]}]
set_load -pin_load 3.40189 [get_ports {o_data[119]}]
set_load -pin_load 3.40189 [get_ports {o_data[118]}]
set_load -pin_load 3.40189 [get_ports {o_data[117]}]
set_load -pin_load 3.40189 [get_ports {o_data[116]}]
set_load -pin_load 3.40189 [get_ports {o_data[115]}]
set_load -pin_load 3.40189 [get_ports {o_data[114]}]
set_load -pin_load 3.40189 [get_ports {o_data[113]}]
set_load -pin_load 3.40189 [get_ports {o_data[112]}]
set_load -pin_load 3.40189 [get_ports {o_data[111]}]
set_load -pin_load 3.40189 [get_ports {o_data[110]}]
set_load -pin_load 3.40189 [get_ports {o_data[109]}]
set_load -pin_load 3.40189 [get_ports {o_data[108]}]
set_load -pin_load 3.40189 [get_ports {o_data[107]}]
set_load -pin_load 3.40189 [get_ports {o_data[106]}]
set_load -pin_load 3.40189 [get_ports {o_data[105]}]
set_load -pin_load 3.40189 [get_ports {o_data[104]}]
set_load -pin_load 3.40189 [get_ports {o_data[103]}]
set_load -pin_load 3.40189 [get_ports {o_data[102]}]
set_load -pin_load 3.40189 [get_ports {o_data[101]}]
set_load -pin_load 3.40189 [get_ports {o_data[100]}]
set_load -pin_load 3.40189 [get_ports {o_data[99]}]
set_load -pin_load 3.40189 [get_ports {o_data[98]}]
set_load -pin_load 3.40189 [get_ports {o_data[97]}]
set_load -pin_load 3.40189 [get_ports {o_data[96]}]
set_load -pin_load 3.40189 [get_ports {o_data[95]}]
set_load -pin_load 3.40189 [get_ports {o_data[94]}]
set_load -pin_load 3.40189 [get_ports {o_data[93]}]
set_load -pin_load 3.40189 [get_ports {o_data[92]}]
set_load -pin_load 3.40189 [get_ports {o_data[91]}]
set_load -pin_load 3.40189 [get_ports {o_data[90]}]
set_load -pin_load 3.40189 [get_ports {o_data[89]}]
set_load -pin_load 3.40189 [get_ports {o_data[88]}]
set_load -pin_load 3.40189 [get_ports {o_data[87]}]
set_load -pin_load 3.40189 [get_ports {o_data[86]}]
set_load -pin_load 3.40189 [get_ports {o_data[85]}]
set_load -pin_load 3.40189 [get_ports {o_data[84]}]
set_load -pin_load 3.40189 [get_ports {o_data[83]}]
set_load -pin_load 3.40189 [get_ports {o_data[82]}]
set_load -pin_load 3.40189 [get_ports {o_data[81]}]
set_load -pin_load 3.40189 [get_ports {o_data[80]}]
set_load -pin_load 3.40189 [get_ports {o_data[79]}]
set_load -pin_load 3.40189 [get_ports {o_data[78]}]
set_load -pin_load 3.40189 [get_ports {o_data[77]}]
set_load -pin_load 3.40189 [get_ports {o_data[76]}]
set_load -pin_load 3.40189 [get_ports {o_data[75]}]
set_load -pin_load 3.40189 [get_ports {o_data[74]}]
set_load -pin_load 3.40189 [get_ports {o_data[73]}]
set_load -pin_load 3.40189 [get_ports {o_data[72]}]
set_load -pin_load 3.40189 [get_ports {o_data[71]}]
set_load -pin_load 3.40189 [get_ports {o_data[70]}]
set_load -pin_load 3.40189 [get_ports {o_data[69]}]
set_load -pin_load 3.40189 [get_ports {o_data[68]}]
set_load -pin_load 3.40189 [get_ports {o_data[67]}]
set_load -pin_load 3.40189 [get_ports {o_data[66]}]
set_load -pin_load 3.40189 [get_ports {o_data[65]}]
set_load -pin_load 3.40189 [get_ports {o_data[64]}]
set_load -pin_load 3.40189 [get_ports {o_data[63]}]
set_load -pin_load 3.40189 [get_ports {o_data[62]}]
set_load -pin_load 3.40189 [get_ports {o_data[61]}]
set_load -pin_load 3.40189 [get_ports {o_data[60]}]
set_load -pin_load 3.40189 [get_ports {o_data[59]}]
set_load -pin_load 3.40189 [get_ports {o_data[58]}]
set_load -pin_load 3.40189 [get_ports {o_data[57]}]
set_load -pin_load 3.40189 [get_ports {o_data[56]}]
set_load -pin_load 3.40189 [get_ports {o_data[55]}]
set_load -pin_load 3.40189 [get_ports {o_data[54]}]
set_load -pin_load 3.40189 [get_ports {o_data[53]}]
set_load -pin_load 3.40189 [get_ports {o_data[52]}]
set_load -pin_load 3.40189 [get_ports {o_data[51]}]
set_load -pin_load 3.40189 [get_ports {o_data[50]}]
set_load -pin_load 3.40189 [get_ports {o_data[49]}]
set_load -pin_load 3.40189 [get_ports {o_data[48]}]
set_load -pin_load 3.40189 [get_ports {o_data[47]}]
set_load -pin_load 3.40189 [get_ports {o_data[46]}]
set_load -pin_load 3.40189 [get_ports {o_data[45]}]
set_load -pin_load 3.40189 [get_ports {o_data[44]}]
set_load -pin_load 3.40189 [get_ports {o_data[43]}]
set_load -pin_load 3.40189 [get_ports {o_data[42]}]
set_load -pin_load 3.40189 [get_ports {o_data[41]}]
set_load -pin_load 3.40189 [get_ports {o_data[40]}]
set_load -pin_load 3.40189 [get_ports {o_data[39]}]
set_load -pin_load 3.40189 [get_ports {o_data[38]}]
set_load -pin_load 3.40189 [get_ports {o_data[37]}]
set_load -pin_load 3.40189 [get_ports {o_data[36]}]
set_load -pin_load 3.40189 [get_ports {o_data[35]}]
set_load -pin_load 3.40189 [get_ports {o_data[34]}]
set_load -pin_load 3.40189 [get_ports {o_data[33]}]
set_load -pin_load 3.40189 [get_ports {o_data[32]}]
set_load -pin_load 3.40189 [get_ports {o_data[31]}]
set_load -pin_load 3.40189 [get_ports {o_data[30]}]
set_load -pin_load 3.40189 [get_ports {o_data[29]}]
set_load -pin_load 3.40189 [get_ports {o_data[28]}]
set_load -pin_load 3.40189 [get_ports {o_data[27]}]
set_load -pin_load 3.40189 [get_ports {o_data[26]}]
set_load -pin_load 3.40189 [get_ports {o_data[25]}]
set_load -pin_load 3.40189 [get_ports {o_data[24]}]
set_load -pin_load 3.40189 [get_ports {o_data[23]}]
set_load -pin_load 3.40189 [get_ports {o_data[22]}]
set_load -pin_load 3.40189 [get_ports {o_data[21]}]
set_load -pin_load 3.40189 [get_ports {o_data[20]}]
set_load -pin_load 3.40189 [get_ports {o_data[19]}]
set_load -pin_load 3.40189 [get_ports {o_data[18]}]
set_load -pin_load 3.40189 [get_ports {o_data[17]}]
set_load -pin_load 3.40189 [get_ports {o_data[16]}]
set_load -pin_load 3.40189 [get_ports {o_data[15]}]
set_load -pin_load 3.40189 [get_ports {o_data[14]}]
set_load -pin_load 3.40189 [get_ports {o_data[13]}]
set_load -pin_load 3.40189 [get_ports {o_data[12]}]
set_load -pin_load 3.40189 [get_ports {o_data[11]}]
set_load -pin_load 3.40189 [get_ports {o_data[10]}]
set_load -pin_load 3.40189 [get_ports {o_data[9]}]
set_load -pin_load 3.40189 [get_ports {o_data[8]}]
set_load -pin_load 3.40189 [get_ports {o_data[7]}]
set_load -pin_load 3.40189 [get_ports {o_data[6]}]
set_load -pin_load 3.40189 [get_ports {o_data[5]}]
set_load -pin_load 3.40189 [get_ports {o_data[4]}]
set_load -pin_load 3.40189 [get_ports {o_data[3]}]
set_load -pin_load 3.40189 [get_ports {o_data[2]}]
set_load -pin_load 3.40189 [get_ports {o_data[1]}]
set_load -pin_load 3.40189 [get_ports {o_data[0]}]
create_clock [get_ports ck]  -name MY_CLK  -period 4  -waveform {0 2}
set_clock_uncertainty 0.07  [get_clocks MY_CLK]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports rst]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_gamma[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_gamma[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_gamma[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_gamma[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_gamma[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_gamma[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_gamma[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_gamma[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_beta[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_beta[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_beta[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_beta[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_beta[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_beta[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_beta[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_beta[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_npu[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_npu[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_npu[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ckg[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ckg[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ckg[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_k[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_k[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_k[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_tile[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_tile[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ifmaps[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ifmaps[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ifmaps[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ofmaps[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ofmaps[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ofmaps[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_ofmaps[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_en_npu]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_ldh_v_n]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_en_hmode]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_en_vmode]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_wr_pipe]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_hmode]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_vmode]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_res]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_npu_ptr]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_tilev]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_tileh]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_ifmaps]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_ofmaps]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports i_data_ev_odd_n]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[127]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[126]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[125]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[124]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[123]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[122]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[121]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[120]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[119]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[118]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[117]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[116]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[115]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[114]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[113]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[112]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[111]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[110]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[109]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[108]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[107]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[106]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[105]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[104]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[103]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[102]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[101]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[100]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[99]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[98]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[97]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[96]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[95]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[94]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[93]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[92]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[91]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[90]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[89]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[88]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[87]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[86]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[85]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[84]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[83]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[82]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[81]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[80]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[79]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[78]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[77]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[76]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[75]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[74]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[73]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[72]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[71]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[70]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[69]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[68]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[67]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[66]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[65]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[64]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[63]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[62]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[61]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[60]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[59]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[58]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[57]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[56]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[55]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[54]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[53]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[52]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[51]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[50]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[49]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[48]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[47]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[46]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[45]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[44]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[43]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[42]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[41]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[40]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[39]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[38]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[37]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[36]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[35]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[34]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[33]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[32]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[0]}]
