###################################################################

# Created by write_sdc on Tue Feb  4 01:50:57 2020

###################################################################
set sdc_version 1.9

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_load -pin_load 3.40189 [get_ports s_tc_hmode]
set_load -pin_load 3.40189 [get_ports s_tc_vmode]
set_load -pin_load 3.40189 [get_ports s_tc_res]
set_load -pin_load 3.40189 [get_ports s_tc_L1]
set_load -pin_load 3.40189 [get_ports s_tc_L2]
set_load -pin_load 3.40189 [get_ports s_tc_L3]
set_load -pin_load 3.40189 [get_ports s_tc_L0]
set_load -pin_load 3.40189 [get_ports s_tc_L4]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[11]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[10]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[9]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[8]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[7]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[6]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[5]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[4]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[3]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[2]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[1]}]
set_load -pin_load 3.40189 [get_ports {i_weight_addr[0]}]
set_load -pin_load 3.40189 [get_ports i_data_ev_odd_n]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[9]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[8]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[7]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[6]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[5]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[4]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[3]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[2]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[1]}]
set_load -pin_load 3.40189 [get_ports {i_data_even_addr[0]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[9]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[8]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[7]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[6]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[5]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[4]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[3]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[2]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[1]}]
set_load -pin_load 3.40189 [get_ports {i_data_odd_addr[0]}]
set_load -pin_load 3.40189 [get_ports o_data_ev_odd_n]
set_load -pin_load 3.40189 [get_ports {o_data_even_addr[9]}]
set_load -pin_load 3.40189 [get_ports {o_data_even_addr[8]}]
set_load -pin_load 3.40189 [get_ports {o_data_even_addr[7]}]
set_load -pin_load 3.40189 [get_ports {o_data_even_addr[6]}]
set_load -pin_load 3.40189 [get_ports {o_data_even_addr[5]}]
set_load -pin_load 3.40189 [get_ports {o_data_even_addr[4]}]
set_load -pin_load 3.40189 [get_ports {o_data_even_addr[3]}]
set_load -pin_load 3.40189 [get_ports {o_data_even_addr[2]}]
set_load -pin_load 3.40189 [get_ports {o_data_even_addr[1]}]
set_load -pin_load 3.40189 [get_ports {o_data_even_addr[0]}]
set_load -pin_load 3.40189 [get_ports {o_data_odd_addr[9]}]
set_load -pin_load 3.40189 [get_ports {o_data_odd_addr[8]}]
set_load -pin_load 3.40189 [get_ports {o_data_odd_addr[7]}]
set_load -pin_load 3.40189 [get_ports {o_data_odd_addr[6]}]
set_load -pin_load 3.40189 [get_ports {o_data_odd_addr[5]}]
set_load -pin_load 3.40189 [get_ports {o_data_odd_addr[4]}]
set_load -pin_load 3.40189 [get_ports {o_data_odd_addr[3]}]
set_load -pin_load 3.40189 [get_ports {o_data_odd_addr[2]}]
set_load -pin_load 3.40189 [get_ports {o_data_odd_addr[1]}]
set_load -pin_load 3.40189 [get_ports {o_data_odd_addr[0]}]
set_load -pin_load 3.40189 [get_ports o_data_wr]
set_load -pin_load 3.40189 [get_ports o_data_wrh]
set_load -pin_load 3.40189 [get_ports o_data_wrh_l_n]
set_load -pin_load 3.40189 [get_ports {o_data[15]}]
set_load -pin_load 3.40189 [get_ports {o_data[14]}]
set_load -pin_load 3.40189 [get_ports {o_data[13]}]
set_load -pin_load 3.40189 [get_ports {o_data[12]}]
set_load -pin_load 3.40189 [get_ports {o_data[11]}]
set_load -pin_load 3.40189 [get_ports {o_data[10]}]
set_load -pin_load 3.40189 [get_ports {o_data[9]}]
set_load -pin_load 3.40189 [get_ports {o_data[8]}]
set_load -pin_load 3.40189 [get_ports {o_data[7]}]
set_load -pin_load 3.40189 [get_ports {o_data[6]}]
set_load -pin_load 3.40189 [get_ports {o_data[5]}]
set_load -pin_load 3.40189 [get_ports {o_data[4]}]
set_load -pin_load 3.40189 [get_ports {o_data[3]}]
set_load -pin_load 3.40189 [get_ports {o_data[2]}]
set_load -pin_load 3.40189 [get_ports {o_data[1]}]
set_load -pin_load 3.40189 [get_ports {o_data[0]}]
create_clock [get_ports ck]  -name MY_CLK  -period 4  -waveform {0 2}
set_clock_uncertainty 0.07  [get_clocks MY_CLK]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports rst]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports hctrl_fc]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_acth[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_actv[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_c_weight[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_c_weight[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[127]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[126]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[125]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[124]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[123]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[122]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[121]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[120]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[119]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[118]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[117]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[116]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[115]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[114]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[113]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[112]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[111]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[110]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[109]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[108]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[107]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[106]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[105]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[104]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[103]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[102]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[101]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[100]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[99]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[98]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[97]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[96]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[95]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[94]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[93]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[92]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[91]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[90]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[89]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[88]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[87]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[86]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[85]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[84]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[83]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[82]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[81]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[80]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[79]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[78]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[77]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[76]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[75]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[74]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[73]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[72]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[71]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[70]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[69]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[68]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[67]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[66]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[65]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[64]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[63]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[62]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[61]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[60]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[59]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[58]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[57]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[56]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[55]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[54]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[53]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[52]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[51]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[50]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[49]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[48]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[47]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[46]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[45]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[44]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[43]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[42]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[41]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[40]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[39]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[38]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[37]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[36]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[35]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[34]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[33]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[32]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[31]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[30]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[29]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[28]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[27]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[26]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[25]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[24]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[23]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[22]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[21]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[20]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[19]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[18]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[17]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[16]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {i_fc_weight[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_CKG[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_CKG[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_CKG[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_KSI[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_KSI[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_KSI[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L0[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L0[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L0[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L0[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L1[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L1[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L1[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L1[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L2[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L2[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L2[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L2[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L3[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L3[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L3[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L3[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L4[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L4[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L4[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {arv_L4[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_en_npu]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_ldh_v_n]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_en_hmode]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_en_vmode]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_wr_pipe]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_en_p]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_en_st]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports ctrl_wr_mem]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_hmode]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_vmode]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_res]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_L1]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_L2]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_L3]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_L0]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports s_tc_L4]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_weight_addr[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports i_data_ev_odd_n]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_even_addr[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {i_data_odd_addr[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports o_data_ev_odd_n]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_even_addr[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_even_addr[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_even_addr[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_even_addr[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_even_addr[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_even_addr[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_even_addr[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_even_addr[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_even_addr[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_even_addr[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_odd_addr[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_odd_addr[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_odd_addr[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_odd_addr[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_odd_addr[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_odd_addr[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_odd_addr[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_odd_addr[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_odd_addr[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data_odd_addr[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports o_data_wr]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports o_data_wrh]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports o_data_wrh_l_n]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {o_data[0]}]
