onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_fsm/cu/ps
add wave -noupdate /tb_fsm/dp/ADDRGEN/ck
add wave -noupdate /tb_fsm/dp/ADDRGEN/rst
add wave -noupdate /tb_fsm/dp/ADDRGEN/int_en_wr_ptr
add wave -noupdate /tb_fsm/dp/ADDRGEN/int_tc_wr
add wave -noupdate /tb_fsm/dp/ADDRGEN/arv_tilev
add wave -noupdate /tb_fsm/dp/ADDRGEN/arv_tileh
add wave -noupdate /tb_fsm/dp/ADDRGEN/arv_tilec
add wave -noupdate /tb_fsm/dp/ADDRGEN/TC_TILEV
add wave -noupdate /tb_fsm/dp/ADDRGEN/TC_TILEH
add wave -noupdate /tb_fsm/dp/ADDRGEN/TC_TILEC
add wave -noupdate /tb_fsm/dp/ADDRGEN/MSB_ADDR
add wave -noupdate /tb_fsm/dp/ADDRGEN/int_en_tilev_ptr
add wave -noupdate /tb_fsm/dp/ADDRGEN/int_en_tileh_ptr
add wave -noupdate /tb_fsm/dp/ADDRGEN/int_en_tilec_ptr
add wave -noupdate /tb_fsm/dp/ADDRGEN/int_tc_tilev
add wave -noupdate /tb_fsm/dp/ADDRGEN/int_tc_tileh
add wave -noupdate /tb_fsm/dp/ADDRGEN/int_tc_tilec
add wave -noupdate /tb_fsm/dp/ADDRGEN/int_tilev_ptr
add wave -noupdate /tb_fsm/dp/ADDRGEN/int_tileh_ptr
add wave -noupdate /tb_fsm/dp/ADDRGEN/int_tilec_ptr
add wave -noupdate /tb_fsm/dp/ADDRGEN/int_arv_tilev
add wave -noupdate /tb_fsm/dp/ADDRGEN/int_arv_tileh
add wave -noupdate /tb_fsm/dp/ADDRGEN/int_arv_tilec
add wave -noupdate /tb_fsm/dp/FIFOPTR/wr_cnt/ck
add wave -noupdate /tb_fsm/dp/FIFOPTR/wr_cnt/rst
add wave -noupdate /tb_fsm/dp/FIFOPTR/wr_cnt/en
add wave -noupdate /tb_fsm/dp/FIFOPTR/wr_cnt/arv
add wave -noupdate /tb_fsm/dp/FIFOPTR/wr_cnt/q
add wave -noupdate /tb_fsm/dp/FIFOPTR/wr_cnt/tc
add wave -noupdate /tb_fsm/dp/FIFOPTR/wr_cnt/int_en
add wave -noupdate /tb_fsm/dp/FIFOPTR/wr_cnt/cnt_out
add wave -noupdate /tb_fsm/dp/FIFOPTR/wr_cnt/terminal_cnt
add wave -noupdate /tb_fsm/dp/FIFOPTR/HMODECNT/ck
add wave -noupdate /tb_fsm/dp/FIFOPTR/HMODECNT/rst
add wave -noupdate /tb_fsm/dp/FIFOPTR/HMODECNT/en
add wave -noupdate /tb_fsm/dp/FIFOPTR/HMODECNT/arv
add wave -noupdate /tb_fsm/dp/FIFOPTR/HMODECNT/q
add wave -noupdate /tb_fsm/dp/FIFOPTR/HMODECNT/tc
add wave -noupdate /tb_fsm/dp/FIFOPTR/HMODECNT/int_en
add wave -noupdate /tb_fsm/dp/FIFOPTR/HMODECNT/cnt_out
add wave -noupdate /tb_fsm/dp/FIFOPTR/HMODECNT/terminal_cnt
add wave -noupdate /tb_fsm/dp/WRPIPE/ck
add wave -noupdate /tb_fsm/dp/WRPIPE/rst
add wave -noupdate /tb_fsm/dp/WRPIPE/EN_RES_PTR
add wave -noupdate /tb_fsm/dp/WRPIPE/TC_RES
add wave -noupdate /tb_fsm/dp/WRPIPE/i_data
add wave -noupdate /tb_fsm/dp/WRPIPE/o_data
add wave -noupdate /tb_fsm/dp/WRPIPE/int_res00
add wave -noupdate /tb_fsm/dp/WRPIPE/int_res01
add wave -noupdate /tb_fsm/dp/WRPIPE/int_res02
add wave -noupdate /tb_fsm/dp/WRPIPE/int_res03
add wave -noupdate /tb_fsm/dp/WRPIPE/int_res10
add wave -noupdate /tb_fsm/dp/WRPIPE/int_res11
add wave -noupdate /tb_fsm/dp/WRPIPE/int_res12
add wave -noupdate /tb_fsm/dp/WRPIPE/int_res13
add wave -noupdate /tb_fsm/dp/WRPIPE/int_res20
add wave -noupdate /tb_fsm/dp/WRPIPE/int_res21
add wave -noupdate /tb_fsm/dp/WRPIPE/int_res22
add wave -noupdate /tb_fsm/dp/WRPIPE/int_res23
add wave -noupdate /tb_fsm/dp/WRPIPE/int_res30
add wave -noupdate /tb_fsm/dp/WRPIPE/int_res31
add wave -noupdate /tb_fsm/dp/WRPIPE/int_res32
add wave -noupdate /tb_fsm/dp/WRPIPE/int_res33
add wave -noupdate /tb_fsm/dp/WRPIPE/int_en_res_ptr
add wave -noupdate /tb_fsm/dp/WRPIPE/int_tc_res
add wave -noupdate /tb_fsm/dp/WRPIPE/int_arv_res
add wave -noupdate /tb_fsm/dp/WRPIPE/int_res_ptr
add wave -noupdate /tb_fsm/dp/WRPIPE/int_d_reg
add wave -noupdate /tb_fsm/dp/WRPIPE/int_q_reg
add wave -noupdate /tb_fsm/cu/ps
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/ck
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/rst
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/ld
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/rd_ptr
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/wr_ptr
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/i_data
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/int_mask
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/int_en
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/SRF/r/en
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/SRF/r/i_data
add wave -noupdate -expand /tb_fsm/dp/DP/DATA_BUFFER/SRF/r/o_data
add wave -noupdate /tb_fsm/dp/WEIGHT_BUFFER/cs
add wave -noupdate /tb_fsm/dp/WEIGHT_BUFFER/rd
add wave -noupdate /tb_fsm/dp/WEIGHT_BUFFER/vmode_ptr
add wave -noupdate /tb_fsm/dp/WEIGHT_BUFFER/hmode_ptr
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/i_kernel
add wave -noupdate -expand /tb_fsm/dp/DP/PE_BLOCK/i_data
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/o_data
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/int_i_data
add wave -noupdate /tb_fsm/cu/ps
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/ck
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/rst
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/ld
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/rd_ptr
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/wr_ptr
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/i_data
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/int_mask
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/int_en
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/SRF/r/en
add wave -noupdate /tb_fsm/dp/DP/DATA_BUFFER/SRF/r/i_data
add wave -noupdate -expand /tb_fsm/dp/DP/DATA_BUFFER/SRF/r/o_data
add wave -noupdate /tb_fsm/dp/WEIGHT_BUFFER/cs
add wave -noupdate /tb_fsm/dp/WEIGHT_BUFFER/rd
add wave -noupdate /tb_fsm/dp/WEIGHT_BUFFER/vmode_ptr
add wave -noupdate /tb_fsm/dp/WEIGHT_BUFFER/hmode_ptr
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/i_kernel
add wave -noupdate -expand /tb_fsm/dp/DP/PE_BLOCK/i_data
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/o_data
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/int_i_data
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/peRowGen(0)/peColGen(0)/peij/ck
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/peRowGen(0)/peColGen(0)/peij/rst
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/peRowGen(0)/peColGen(0)/peij/en
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/peRowGen(0)/peColGen(0)/peij/k
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/peRowGen(0)/peColGen(0)/peij/i_data
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/peRowGen(0)/peColGen(0)/peij/o_data
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/peRowGen(0)/peColGen(0)/peij/int_en
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/peRowGen(0)/peColGen(0)/peij/q_im
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/peRowGen(0)/peColGen(0)/peij/sgnext
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/peRowGen(0)/peColGen(0)/peij/d_acc
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/peRowGen(0)/peColGen(0)/peij/q_acc
add wave -noupdate /tb_fsm/dp/DP/PE_BLOCK/peRowGen(0)/peColGen(0)/peij/q_k
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {380471 ps} 0}
configure wave -namecolwidth 266
configure wave -valuecolwidth 206
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 1
configure wave -timelineunits ns
update
WaveRestoreZoom {1501250 ps} {2026250 ps}
