onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_fsm/dp/CKG_MASK_CTRL/ck
add wave -noupdate /tb_fsm/cu/ps
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/s_tc_tilev
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/s_tc_tileh
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/s_tc_tileb
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/s_tc_tilec
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/s_tc_tilev
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/s_tc_tileh
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/s_tc_tileb
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/s_tc_tilec
add wave -noupdate /tb_fsm/dp/CKG_MASK_CTRL/rst
add wave -noupdate /tb_fsm/dp/CKG_MASK_CTRL/ck_en
add wave -noupdate /tb_fsm/dp/CKG_MASK_CTRL/ckg_rsel
add wave -noupdate /tb_fsm/dp/CKG_MASK_CTRL/ckg_csel
add wave -noupdate /tb_fsm/dp/CKG_MASK_CTRL/ckg_mask
add wave -noupdate /tb_fsm/dp/CKG_MASK_CTRL/ckg_mask_lt
add wave -noupdate /tb_fsm/dp/CKG_MASK_CTRL/ckg_rmask
add wave -noupdate /tb_fsm/dp/CKG_MASK_CTRL/ckg_cmask
add wave -noupdate /tb_fsm/dp/CKG_MASK_CTRL/s_ckg
add wave -noupdate /tb_fsm/dp/CKG_MASK_CTRL/int_en_ckg_r
add wave -noupdate /tb_fsm/dp/CKG_MASK_CTRL/int_en_ckg_c
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/ck
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/rst
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/inc
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/arv_tilev
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/arv_tileh
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/arv_tileb
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/arv_tilec
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/even_addr
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/odd_addr
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_en_tilev_ptr
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_en_tileh_ptr
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_en_tileb_ptr
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_en_tilec_ptr
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_tc_tilev
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_tc_tileh
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_tc_tileb
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_tc_tilec
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_tilev_ptr
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_tileh_ptr
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_tileb_ptr
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_tilec_ptr
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_arv_tilev
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_arv_tileh
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_arv_tileb
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_arv_tilec
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_en_page_ptr
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_tc_page
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_page_ptr
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_inc_even
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_inc_odd
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_even_offset
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_odd_offset
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_offset_val
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_even_addr
add wave -noupdate /tb_fsm/dp/RD_ADDR_GEN/int_odd_addr
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/ck
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/rst
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/inc
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/arv_tilev
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/arv_tileh
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/arv_tileb
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/arv_tilec
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/even_addr
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/odd_addr
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_en_tilev_ptr
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_en_tileh_ptr
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_en_tileb_ptr
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_en_tilec_ptr
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_tc_tilev
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_tc_tileh
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_tc_tileb
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_tc_tilec
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_tilev_ptr
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_tileh_ptr
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_tileb_ptr
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_tilec_ptr
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_arv_tilev
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_arv_tileh
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_arv_tileb
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_arv_tilec
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_en_page_ptr
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_tc_page
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_page_ptr
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_inc_even
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_inc_odd
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_even_offset
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_odd_offset
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_offset_val
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_even_addr
add wave -noupdate /tb_fsm/dp/WR_ADDR_GEN/int_odd_addr
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {957354 ps} 0}
configure wave -namecolwidth 254
configure wave -valuecolwidth 40
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 1
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {52500 ns}
